# Generated by Django 6.0 on 2025-12-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RECEPCION', 'Recepción de Documentos'), ('REVISION', 'Revisión Legal'), ('PRESENTACION', 'Presentación Oficial'), ('APROBACION', 'Aprobación')], default='RECEPCION', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='crm.client')),
            ],
        ),
    ]
