# Generated by Django 6.0 on 2025-12-04 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='identity_doc',
            field=models.CharField(blank=True, help_text='DNI, NIE, Pasaporte', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_collaborator',
            field=models.BooleanField(default=False, help_text='Es un socio comercial con precios preferenciales?'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_friendly_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'En Proceso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('CUP', 'Peso Cubano')], default='EUR', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('CUP', 'Peso Cubano')], default='EUR', max_length=3)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('STRIPE', 'Pasarela Online')], default='TRANSFER', max_length=20)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.order')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('LEGALIZATION', 'Legalización Minjus/Consulado'), ('VISA', 'Visado/Cita'), ('SHIPPING', 'Envío/Paquetería'), ('OTHER', 'Otro')], default='LEGALIZATION', max_length=20)),
                ('document_type', models.CharField(blank=True, help_text='Ej: Nacimiento, Penales', max_length=100)),
                ('titular_name', models.CharField(blank=True, help_text='Nombre del titular del documento', max_length=255)),
                ('status', models.CharField(choices=[('INIT', 'Iniciado/Solicitado'), ('MINJUS_IN', 'Entrada Minjus'), ('MINJUS_OUT', 'Salida Minjus'), ('CONSULATE_IN', 'Entrada Consulado'), ('CONSULATE_OUT', 'Salida Consulado'), ('READY', 'Listo para Entrega'), ('DELIVERED', 'Entregado')], default='INIT', max_length=20)),
                ('current_location', models.CharField(default='Oficina Central', help_text='Dónde está el papel físicamente', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Coste interno', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio al cliente', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
