# Generated by Django 6.0 on 2025-12-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_address_client_identity_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
