# Generated by Django 6.0 on 2025-12-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_order_total_cost_order_total_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('EXPRESS', 'Express (Urgente)')], default='NORMAL', max_length=10),
        ),
    ]
