# Generated by Django 6.0 on 2025-12-04 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_serviceitem_deadline_serviceitem_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Gestor responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='global_status',
            field=models.CharField(choices=[('NEW_REQUEST', 'Solicitud Nueva'), ('PENDING_PAYMENT', 'Pendiente de Pago'), ('IN_PROCESS_PARTIAL', 'En Proceso (Pago Parcial)'), ('IN_PROCESS_PAID', 'En Proceso (Pagado)'), ('READY_DELIVERY', 'Finalizado/Para Entrega'), ('CLOSED', 'Cerrado/Archivado')], default='NEW_REQUEST', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Pago Parcial'), ('PAID', 'Pagado Completo')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total pagado por el cliente', max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='assigned_tramitador',
            field=models.ForeignKey(blank=True, help_text='Tramitador asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='final_document',
            field=models.FileField(blank=True, help_text='Documento final legalizado', null=True, upload_to='final_documents/'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas específicas del trámite'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='phase_dates',
            field=models.JSONField(blank=True, default=dict, help_text='Fechas de cada fase del proceso'),
        ),
    ]
