# Generated by Django 6.0 on 2025-12-04 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_order_assigned_to_order_global_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='destination_account',
            field=models.CharField(choices=[('SPAIN', 'Cuenta España'), ('CUBA', 'Cuenta Cuba'), ('OTHER', 'Otra')], default='SPAIN', help_text='Cuenta de destino', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_sent',
            field=models.BooleanField(default=False, help_text='¿Se envió recibo al cliente?'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('STATUS_CHANGE', 'Cambio de Estado'), ('PAYMENT', 'Registro de Pago'), ('EMAIL', 'Email Enviado'), ('NOTE', 'Nota Añadida'), ('ASSIGNMENT', 'Asignación'), ('DOCUMENT_UPLOAD', 'Documento Subido'), ('SERVICE_ADDED', 'Servicio Añadido')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de la acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='crm.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
            },
        ),
    ]
