# Generated by Django 6.0 on 2025-12-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_payment_destination_account_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='legalization_type',
            field=models.CharField(blank=True, help_text='Ej: Apostilla, Legalización Consular', max_length=100),
        ),
    ]
