# Generated by Django 6.0 on 2025-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_serviceitem_legalization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='delivery_destination',
            field=models.CharField(choices=[('INTERNACIONAL', 'Envío Internacional (España)'), ('HABANA', 'Recoger en La Habana'), ('CAMAGUEY', 'Recoger en Camagüey')], default='INTERNACIONAL', help_text='Destino de entrega del documento', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='logistics_status',
            field=models.CharField(choices=[('NA', 'N/A (En Gestión)'), ('PENDING_PICKUP', 'Pendiente de Recogida'), ('LOCAL_DELIVERY', 'En Reparto Local'), ('INTER_OFFICE', 'Tránsito Inter-Oficinas'), ('FINAL_SHIPPING', 'Envío Paquetería Final'), ('RECEIVING', 'En Recepción/Entrante'), ('DELIVERED', 'Entregado')], default='NA', help_text='¿Qué acción logística ocurre?', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='responsible',
            field=models.CharField(choices=[('OFICINA_CUBA', 'Oficina Cuba'), ('OFICINA_ESPANA', 'Oficina España'), ('GESTOR_CAMPO', 'Gestor de Campo'), ('AGENCIA_INTERNA', 'Agencia Interna'), ('COURIER_EXTERNO', 'Courier Externo'), ('CLIENTE', 'Cliente/Asociado')], default='OFICINA_CUBA', help_text='¿Quién tiene el documento?', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='current_location',
            field=models.CharField(choices=[('OFICINA_HABANA', 'Oficina Habana'), ('OFICINA_ESPANA', 'Oficina España'), ('VICECONSULADO_CAMAGUEY', 'Viceconsulado Camagüey'), ('DOMICILIO_CLIENTE', 'Domicilio Cliente'), ('OFICINA_ASOCIADO', 'Oficina Asociado'), ('MINJUS', 'MINJUS'), ('CONSULADO', 'Consulado')], default='OFICINA_HABANA', help_text='¿Dónde está el documento físicamente?', max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='status',
            field=models.CharField(choices=[('INIT', 'Iniciado/Solicitado'), ('PENDING_RECEIVE', 'Pendiente Recibir Documento'), ('RECEIVED', 'Documento Recibido'), ('MINJUS_IN', 'Entrada Minjus'), ('MINJUS_OUT', 'Salida Minjus'), ('CONSULATE_IN', 'Entrada Consulado'), ('CONSULATE_OUT', 'Salida Consulado'), ('LEGALIZED', 'Legalizado'), ('SENT_SPAIN', 'Enviado a España'), ('SENT_CLIENT', 'Enviado al Cliente'), ('SENT_CAMAGUEY', 'Enviado a Camagüey'), ('READY_PICKUP', 'Listo para Recoger'), ('READY', 'Listo para Entrega'), ('DELIVERED', 'Entregado')], default='INIT', max_length=20),
        ),
    ]
